### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Gabuabuu** [albcorreia/tprodutivo#1]
Uma sugestão seria você hospedar seu projeto no Github Pages ou na vercel, assim os usuários poderiam testar sua aplicação e ter uma visualização melhor do funcionamento do projeto.

**Comment by albcorreia** [comment]
Eu agradeço por escreveres essa sugestão para mim. Ainda mais, por ser a fase em que estou me acostumando a usar o github. Obrigado de novo e vou procurar fazer isto que tu me sugeriu.
